### PR TITLE
Temporary Place Holder Page

### PR DESCRIPTION
**Pull request by scottrkehr**
### Updates:
- Place Holder Landing Page with Logo
- ESLint Configuration
- Prettier Configuration
- Jest Configuration
- SCSS Variables

### CODE REVIEW

**Comment by scottrkehr** [comment]
[Landing Page](https://trello.com/c/SBA02x4U/5-landing-page)

**Comment by scottrkehr** [comment]
[Linting and Formatting](https://trello.com/c/ZQt6tznl/19-linting-and-formatting)

**Comment by scottrkehr** [comment]
[SCSS Variables](https://trello.com/c/OPkSwrOa/12-scss-variables)

**Comment by scottrkehr** [comment]
[Unit Tests](https://trello.com/c/0VO1L3Uu/21-unit-tests)

**Review by hallmanm — APPROVED** [review]

**Pull request merged**
